version: '3'

services:
  multi-tts:
    image: multi-tts
    container_name: multi-tts
    volumes:
      - ./models:/root/.local/share/tts
    ports:
      - "15002:5002"
    restart: always

  single-tts:
    image: single-tts
    container_name: single-tts
    volumes:
      - ./models:/root/.local/share/tts
    ports:
      - "15003:5002"
    restart: always

  whisper:
    container_name: whisper
    image: datmt-whisper
    ports:
      - "15004:9000"
    restart: always
